#include "hgemv_launch.cuh"

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    TORCH_BINDING_COMMON_EXTENSION(hgemv_k32_f16)
    TORCH_BINDING_COMMON_EXTENSION(hgemv_k128_f16x4)
    TORCH_BINDING_COMMON_EXTENSION(hgemv_k16_f16)
}
