#include "swish_launch.cuh"

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    TORCH_BINDING_COMMON_EXTENSION(swish_f32)
    TORCH_BINDING_COMMON_EXTENSION(swish_f32x4)
    TORCH_BINDING_COMMON_EXTENSION(swish_f16)
    TORCH_BINDING_COMMON_EXTENSION(swish_f16x2)
    TORCH_BINDING_COMMON_EXTENSION(swish_f16x8)
    TORCH_BINDING_COMMON_EXTENSION(swish_f16x8_pack)
}
