#include "sigmoid_launch.cuh"

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    TORCH_BINDING_COMMON_EXTENSION(sigmoid_f32)
    TORCH_BINDING_COMMON_EXTENSION(sigmoid_f32x4)
    TORCH_BINDING_COMMON_EXTENSION(sigmoid_f16)
    TORCH_BINDING_COMMON_EXTENSION(sigmoid_f16x2)
    TORCH_BINDING_COMMON_EXTENSION(sigmoid_f16x8)
    TORCH_BINDING_COMMON_EXTENSION(sigmoid_f16x8_pack)
}
