#include "layernorm.cuh"

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    TORCH_BINDING_COMMON_EXTENSION(layer_norm_f32)
    TORCH_BINDING_COMMON_EXTENSION(layer_norm_f32x4)
    TORCH_BINDING_COMMON_EXTENSION(layer_norm_f16_f16)
    TORCH_BINDING_COMMON_EXTENSION(layer_norm_f16_f32)
    TORCH_BINDING_COMMON_EXTENSION(layer_norm_f16x2_f16)
    TORCH_BINDING_COMMON_EXTENSION(layer_norm_f16x8_f16)
    TORCH_BINDING_COMMON_EXTENSION(layer_norm_f16x8_pack_f16)
    TORCH_BINDING_COMMON_EXTENSION(layer_norm_f16x8_pack_f32)
}
